### ISSUE TITLE
How do I use this package with CUDA11.8?

### ISSUE THREAD

**Issue by akshetpandey** [conda-forge/kaldi-feedstock#46]
### Comment:

It seems that the package assumes availability of cuda 12. Is it possible to build this package with 11.8 instead?

**Comment by h-vetinari** [comment]
There were builds for 11.2 as well, which are installable when you're on 11.8. In any case, I've added the 11.8 builds, as 11.2 will soon be removed.

**Comment by akshetpandey** [comment]
This might be me not understanding how to specify exact versions, but how do I get it to install the 11.8 version of kaldi? No matter what I do, it still builds with cuda12

**Comment by h-vetinari** [comment]
I'm not sure what you mean by "it still builds with cuda12" - are you using kaldi, or compiling something on top? By default, conda will pick the highest available CUDA version for which we have builds, and which your local CUDA driver supports. Check the output of `conda info` and look for the `__cuda` virtual package, which will tell you which version of the driver conda has detected on your system.

If need be, you can also use `CONDA_OVERRIDE_CUDA`. Or perhaps you're on a very old conda version. Details [here](https://conda-forge.org/docs/maintainer/knowledge_base/#cuda-builds) (particularly the "Note" box).

**Comment by akshetpandey** [comment]
I am trying to build a docker container. The base image is `nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04`. I am using micromamba, but if that is going to be an issue I can switch to conda. 

The container should already contain cuda11.8 libraries, but it doesn't seem like micromamba is picking them up.

```
root@8adf20f82637:/# micromamba info

       libmamba version : 1.5.7
     micromamba version : 1.5.7
           curl version : libcurl/8.5.0 OpenSSL/3.2.1 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /root/.mambarc
 populated config files : /root/.condarc
       virtual packages : __unix=0=0
                          __linux=6.6.16=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v2
               channels :
       base environment : /opt/conda
               platform : linux-64
```

I am installing `montreal-forced-aligner`, but trying to get mamba to install the cuda11.8 version of kaldi. Creating a conda env installs these packages:

```
root@8adf20f82637:/# micromamba -p /env/ list
...
  cuda-cudart                           12.4.99       hd3aeb46_0             conda-forge
  cuda-cudart_linux-64                  12.4.99       h59595ed_0             conda-forge
  cuda-nvrtc                            12.4.99       hd3aeb46_0             conda-forge
  cuda-nvtx                             12.4.99       h59595ed_0             conda-forge
  cuda-version                          12.4          h3060b56_3             conda-forge
...
```

These environment variables are set by the base image:
```
CUDA_VERSION="11.8.0"
NCCL_VERSION="2.15.5-1"
NVARCH="x86_64"
NVIDIA_DRIVER_CAPABILITIES="compute,utility"
NVIDIA_PRODUCT_NAME="CUDA"
NVIDIA_REQUIRE_CUDA="cuda>=11.8 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471"
NVIDIA_VISIBLE_DEVICES="all"
NV_CUDA_COMPAT_PACKAGE="cuda-compat-11-8"
NV_CUDA_CUDART_VERSION="11.8.89-1"
NV_CUDA_LIB_VERSION="11.8.0-1"
NV_CUDNN_PACKAGE="libcudnn8=8.9.6.50-1+cuda11.8"
NV_CUDNN_PACKAGE_NAME="libcudnn8"
NV_CUDNN_VERSION="8.9.6.50"
NV_LIBCUBLAS_PACKAGE="libcublas-11-8=11.11.3.6-1"
NV_LIBCUBLAS_PACKAGE_NAME="libcublas-11-8"
NV_LIBCUBLAS_VERSION="11.11.3.6-1"
NV_LIBCUSPARSE_VERSION="11.7.5.86-1"
NV_LIBNCCL_PACKAGE="libnccl2=2.15.5-1+cuda11.8"
NV_LIBNCCL_PACKAGE_NAME="libnccl2"
NV_LIBNCCL_PACKAGE_VERSION="2.15.5-1"
NV_LIBNPP_PACKAGE="libnpp-11-8=11.8.0.86-1"
NV_LIBNPP_VERSION="11.8.0.86-1"
NV_NVTX_VERSION="11.8.86-1"
```

I don't see any usage of CONDA_OVERRIDE_CUDA on the internet, but I can try building with that set and see if that works.

**Comment by h-vetinari** [comment]
So the issue is that conda/micromamba cannot find the CUDA driver - i.e. `__cuda` is missing in the following list:
```
       virtual packages : __unix=0=0
                          __linux=6.6.16=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v2
```

It could be that the driver is not in the image, or that it's in a place that conda/micromamba doesn't find (or doesn't have the rights to read). So because no `__cuda` package is found, you're mostly going to get non-CUDA versions of packages, or - where you're forcing the solver to install gpu packages anyway - you'll get the newest CUDA, since it's not constrained by the missing local driver version.

`CONDA_OVERRIDE_CUDA` should fix both those issues. I already linked some docs, though there's more if your search for it (e.g. [here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages)).

**Comment by akshetpandey** [comment]
Yeah, its expected that it can't find the cuda drivers, since they won't be available inside docker during build. 

Using CONDA_OVERRIDE_CUDA seems to have worked!
